### PR TITLE
Create Misc2000GarageDoorOpener.js

### PR DESCRIPTION
**Pull request by misc2000**
This is my Handler for a Hörmann Garage Door Opener

### CODE REVIEW

**Comment by snowdd1** [comment]
Where is the timer thing, or didn't you need it after all?

**Comment by misc2000** [comment]
I am testing right now. I will update it when it work.

**Comment by misc2000** [comment]
timer to set the open state now also work in the garage door handler.
But I found a case that is not perfect when you open the door over HK with the iPhone and close it from the KNX side. Then the current status is not shown perfect at the phone (HK side).
I will debug this tomorrow evening and will upload the new version after i catches this issue...

**Comment by snowdd1** [comment]
Hi misc2000, please create a new pull request for the update.

**Comment by misc2000** [comment]
Yes will do. But I need to delay the test 1-2 days (no time right now)

**Comment by snowdd1** [comment]
Hi Michael, if you find time could you put a description of your handler for the German homebridge-knx wiki at  
https://github.com/snowdd1/homebridge-knx-de/wiki/Handler:-Misc2000GarageDoorOpener

You can find a German example description page here: https://github.com/snowdd1/homebridge-knx-de/wiki/Handler:-GiraJalousieActuator

Thanks
Raoul

**Pull request merged**
