### PR TITLE
First implementation of Busch Jaeger Waveline Aktors

### PR DESCRIPTION
**Pull request by ctschach**

### CODE REVIEW

**Comment by snowdd1** [comment]
The contact sensor just responses with 0 closed and >1 open? Why do you first calculate knxValue/255*100 before comparing to ZERO?

**Comment by ctschach** [comment]
You are absolutely right...this is not needed.I just removed it...

**Comment by snowdd1** [comment]
Did the timeout help with the answers? Is it tested and ready to merge?

**Comment by ctschach** [comment]
Yes, the timeout helped to update the TargetPosition back to CurrentPosition. And yes, it's tested and working on my end...

**Pull request merged**
